### ISSUE TITLE
Missing currency KWD

### ISSUE THREAD

**Issue by Xedros** [universalbasket/price-parser#2]
Hi,

We found a new currency Kuwaiti dinar (KWD). Can you add this please?

![image](https://user-images.githubusercontent.com/34474056/39982005-9b533ed6-575b-11e8-807b-b2df04815a01.png)

https://backoffice.automationcloud.net/jobs/af9d159a-ed52-423d-be68-8cba512e8b19/executions

Thanks!

**Comment by inca** [comment]
Done
